// <auto-generated />
namespace Stomik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class plusLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(plusLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "202203200552192_plusLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
